CREATE TABLE CATEGORY(
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CATEGORY (NAME) VALUES ('Lazer');
INSERT INTO CATEGORY (NAME) VALUES ('Alimentação');
INSERT INTO CATEGORY (NAME) VALUES ('Supermercado');
INSERT INTO CATEGORY (NAME) VALUES ('Farmácia');
INSERT INTO CATEGORY (NAME) VALUES ('Outros');